"use client";

// CertSection — the Permit Auto-Filler UI on a booking status page.
//
// Shows three states based on booking.status:
//
//   • status ∈ {arrived}                    → "Inspection in progress" (info only)
//   • status ∈ {inspected_pass, inspected_fail}
//     and no cert yet                       → "Generate certificate" form
//   • status ∈ {certified, submitted, accepted}
//     OR cert already exists                → Cert summary + Download + Escalations

import { useState } from "react";
import { useRouter } from "next/navigation";

const COPPER = "#E07A2F";

type Escalation = { field: string; reason: string };

type CertPayload = {
  result: "PASS" | "FAIL" | "PASS_WITH_NOTES";
  resultRationale: string;
  inspectionDate: string;
  validUntil: string;
  escalations: Escalation[];
  source: "anthropic" | "demo-stub";
};

export function CertSection({
  bookingId,
  status,
  certPayload,
}: {
  bookingId: string;
  status: string;
  certPayload: CertPayload | null;
}) {
  const router = useRouter();
  const [pass, setPass] = useState(true);
  const [notes, setNotes] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const hasCert = !!certPayload;
  const showForm =
    !hasCert && (status === "inspected_pass" || status === "inspected_fail");
  const showInProgress = status === "en_route" || status === "arrived";

  // Default the pass state to whatever the inspector set during status walk
  if (!hasCert && status === "inspected_fail" && pass) setPass(false);

  async function handleGenerate() {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`/api/booking/${bookingId}/cert`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pass, systemNotes: notes }),
      });
      const data = await res.json();
      if (!data.ok) {
        setError(data.message ?? "Cert generation failed.");
        setBusy(false);
        return;
      }
      router.refresh();
    } catch {
      setError("Couldn't reach the server.");
      setBusy(false);
    }
  }

  // ─── Existing cert: show summary + download + escalations ───
  if (hasCert && certPayload) {
    const validUntilDate = new Date(certPayload.validUntil);
    const validUntilLabel = validUntilDate.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
    const tone = certPayload.result === "FAIL" ? "fail" : "complete";
    const toneStyles = {
      fail: { fg: "#fca5a5", bg: "rgba(239,68,68,0.06)", border: "rgba(239,68,68,0.3)" },
      complete: { fg: "#86efac", bg: "rgba(34,197,94,0.06)", border: "rgba(34,197,94,0.3)" },
    }[tone];

    const sourceLabel =
      certPayload.source === "anthropic"
        ? "Generated by Claude · Permit Auto-Filler"
        : "Generated in demo mode (deterministic stub) · Permit Auto-Filler";

    return (
      <div
        className="rounded-2xl border p-6 sm:p-7 space-y-5"
        style={{ background: toneStyles.bg, borderColor: toneStyles.border }}
      >
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <div
              className="text-[10px] tracking-[2.5px] uppercase mb-2 font-medium"
              style={{ color: toneStyles.fg, fontFamily: "var(--font-space-grotesk)" }}
            >
              {certPayload.result === "FAIL"
                ? "Cert generated · failed inspection"
                : certPayload.result === "PASS_WITH_NOTES"
                ? "Cert generated · passed with notes"
                : "Cert generated · passed"}
            </div>
            <h3
              className="text-xl sm:text-2xl font-semibold text-white tracking-[-0.5px]"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              Certificate ready for review.
            </h3>
            <p className="text-sm text-white/65 mt-1">{sourceLabel}</p>
          </div>
          <a
            href={`/api/booking/${bookingId}/cert.pdf`}
            target="_blank"
            rel="noopener"
            className="px-6 py-3 rounded-lg font-medium text-white whitespace-nowrap transition"
            style={{
              background: COPPER,
              boxShadow: "0 6px 24px rgba(224,122,47,0.3)",
            }}
          >
            Download PDF →
          </a>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
            <div
              className="text-[10px] tracking-[2px] uppercase text-white/40 mb-1"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              Inspection date
            </div>
            <div
              className="text-base font-semibold text-white tracking-[-0.3px]"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              {certPayload.inspectionDate}
            </div>
          </div>
          <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
            <div
              className="text-[10px] tracking-[2px] uppercase text-white/40 mb-1"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              Cert valid through
            </div>
            <div
              className="text-base font-semibold text-white tracking-[-0.3px]"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              {validUntilLabel}
            </div>
          </div>
        </div>

        <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-4">
          <div
            className="text-[10px] tracking-[2px] uppercase text-white/40 mb-2"
            style={{ fontFamily: "var(--font-space-grotesk)" }}
          >
            Inspector findings
          </div>
          <p className="text-sm text-white/80 leading-relaxed">{certPayload.resultRationale}</p>
        </div>

        {certPayload.escalations.length > 0 && (
          <div
            className="rounded-lg border p-4"
            style={{
              borderColor: "rgba(234,179,8,0.3)",
              background: "rgba(234,179,8,0.04)",
            }}
          >
            <div
              className="text-[10px] tracking-[2px] uppercase mb-3 font-medium flex items-center gap-2"
              style={{ color: "#fde68a", fontFamily: "var(--font-space-grotesk)" }}
            >
              ⚠ Items for human review · {certPayload.escalations.length}
            </div>
            <div className="space-y-3">
              {certPayload.escalations.map((e, i) => (
                <div key={i} className="flex gap-3">
                  <span
                    className="font-mono text-[11px] uppercase tracking-wide flex-shrink-0 mt-0.5"
                    style={{ color: COPPER }}
                  >
                    {e.field}
                  </span>
                  <span className="text-sm text-white/75 leading-relaxed">{e.reason}</span>
                </div>
              ))}
            </div>
            <p className="text-xs text-white/50 mt-3 italic">
              Resolve these before submission to the county. The cert PDF flags them too.
            </p>
          </div>
        )}
      </div>
    );
  }

  // ─── Awaiting inspection ───
  if (showInProgress) {
    return (
      <div
        className="rounded-2xl border p-6"
        style={{
          background: "linear-gradient(135deg, rgba(234,179,8,0.06) 0%, rgba(15,25,35,0.6) 100%)",
          borderColor: "rgba(234,179,8,0.25)",
        }}
      >
        <div
          className="text-[10px] tracking-[2px] uppercase text-white/45 mb-2"
          style={{ fontFamily: "var(--font-space-grotesk)" }}
        >
          Inspection in progress
        </div>
        <h3
          className="text-lg font-semibold text-white tracking-[-0.3px]"
          style={{ fontFamily: "var(--font-space-grotesk)" }}
        >
          Cert generation unlocks once the inspector marks pass or fail.
        </h3>
      </div>
    );
  }

  // ─── Form to generate ───
  if (showForm) {
    return (
      <div
        className="rounded-2xl border p-6 sm:p-7"
        style={{
          background: "linear-gradient(135deg, rgba(224,122,47,0.06) 0%, rgba(15,25,35,0.6) 100%)",
          borderColor: "rgba(224,122,47,0.3)",
        }}
      >
        <div
          className="text-[10px] tracking-[2.5px] uppercase mb-2 font-medium"
          style={{ color: COPPER, fontFamily: "var(--font-space-grotesk)" }}
        >
          Permit Auto-Filler
        </div>
        <h3
          className="text-xl sm:text-2xl font-semibold text-white tracking-[-0.5px] mb-2"
          style={{ fontFamily: "var(--font-space-grotesk)" }}
        >
          Generate the county certificate.
        </h3>
        <p className="text-sm text-white/65 leading-relaxed mb-5 max-w-2xl">
          Claude reads the booking, the property data, and the inspector&apos;s findings, fills the {`county form`}, and flags anything ambiguous for human review. ~30 seconds.
        </p>

        <div className="space-y-4 mb-5">
          <div>
            <span
              className="block text-[10px] tracking-[2px] uppercase text-white/45 mb-2"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              Inspection result
            </span>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setPass(true)}
                className="flex-1 px-4 py-2.5 rounded-md text-sm font-semibold tracking-wide uppercase transition"
                style={{
                  background: pass
                    ? "rgba(34,197,94,0.15)"
                    : "rgba(255,255,255,0.03)",
                  color: pass ? "#86efac" : "rgba(255,255,255,0.5)",
                  border: pass
                    ? "1px solid rgba(34,197,94,0.4)"
                    : "1px solid rgba(255,255,255,0.1)",
                  fontFamily: "var(--font-space-grotesk)",
                  letterSpacing: "1.5px",
                }}
              >
                Passed
              </button>
              <button
                type="button"
                onClick={() => setPass(false)}
                className="flex-1 px-4 py-2.5 rounded-md text-sm font-semibold tracking-wide uppercase transition"
                style={{
                  background: !pass
                    ? "rgba(239,68,68,0.15)"
                    : "rgba(255,255,255,0.03)",
                  color: !pass ? "#fca5a5" : "rgba(255,255,255,0.5)",
                  border: !pass
                    ? "1px solid rgba(239,68,68,0.4)"
                    : "1px solid rgba(255,255,255,0.1)",
                  fontFamily: "var(--font-space-grotesk)",
                  letterSpacing: "1.5px",
                }}
              >
                Failed
              </button>
            </div>
          </div>

          <label className="block">
            <span
              className="block text-[10px] tracking-[2px] uppercase text-white/45 mb-2"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              Inspector notes (free text — Claude reasons over this)
            </span>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={4}
              placeholder="e.g., Conventional drain field, est. 22 yrs old. Baffles intact. Liquid level at outlet invert. No surface effluent. D-box clear."
              className="w-full px-4 py-3 bg-white/[0.04] border border-white/[0.1] rounded-lg text-white placeholder:text-white/30 focus:outline-none focus:border-[#E07A2F]/50 transition resize-none"
            />
          </label>
        </div>

        {error && (
          <p className="text-sm mb-4" style={{ color: "#fca5a5" }}>
            {error}
          </p>
        )}

        <button
          type="button"
          onClick={handleGenerate}
          disabled={busy}
          className="px-7 py-3.5 rounded-lg font-medium text-white transition disabled:opacity-50 disabled:cursor-not-allowed"
          style={{
            background: COPPER,
            boxShadow: busy ? "none" : "0 8px 30px rgba(224,122,47,0.3)",
          }}
        >
          {busy ? "Working…" : "Generate certificate →"}
        </button>

        <p className="text-xs text-white/40 mt-4">
          Without an Anthropic API key configured, the agent runs in deterministic demo mode — same fields, no LLM call. Production wires the real Claude call.
        </p>
      </div>
    );
  }

  return null;
}
